export const CREATE_QUESTIONNAIRE_START = "CREATE_QUESTIONNAIRE_START";
export const CREATE_QUESTIONNAIRE_SUCCESS = "CREATE_QUESTIONNAIRE_SUCCESS";
export const CREATE_QUESTIONNAIRE_FAIL = "CREATE_QUESTIONNAIRE_FAIL";

export const FETCH_QUESTIONAIRES_START = "FETCH_QUESTIONAIRES_START";
export const FETCH_QUESTIONAIRES_SUCCESS = "FETCH_QUESTIONAIRES_SUCCESS";
export const FETCH_QUESTIONAIRES_FAIL = "FETCH_QUESTIONAIRES_FAIL";

export const POST_ANSWERS_START = "POST_ANSWERS_START";
export const POST_ANSWERS_SUCCESS = "POST_ANSWERS_SUCCESS";
export const POST_ANSWERS_FAIL = "POST_ANSWERS_FAIL";